# /etc/nginx/conf.d/mast-wis-control.conf

server {
    set $proxy_port 8000;
    set $proxy_external_ip 10.23.3.73;

    listen 8000;

    # mast-dash (Django GUI)
    location /mast-dash/ {
        proxy_pass http://localhost:8010/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Proxy-Base /mast-dash/;
        proxy_set_header X-Proxy-Port ${proxy_port};
        proxy_set_header X-Proxy-External-IP ${proxy_external_ip};
    }

    location /mast-backend/ {
        proxy_pass http://localhost:8002/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Proxy-Base /mast-backend/;
        proxy_set_header X-Proxy-Port ${proxy_port};
        proxy_set_header X-Proxy-External-IP ${proxy_external_ip};
    }

    # wao-safety (Grafana)
    location /wao-safety/ {
        proxy_pass http://10.23.1.25:3000/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Proxy-Base /wao-safety/;
        proxy_set_header X-Proxy-Port ${proxy_port};
        proxy_set_header X-Proxy-External-IP ${proxy_external_ip};
    }

    # mast-netdata (Netdata)
    location /mast-netdata/ {
        proxy_pass http://localhost:19999/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Proxy-Base /mast-netdata/;
        proxy_set_header X-Proxy-Port ${proxy_port};
    }

    # mast-share (File System Service)
    location /mast-share/ {
        proxy_pass http://localhost:8008/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Proxy-Base /mast-share/;
        proxy_set_header X-Proxy-Port ${proxy_port};
        proxy_set_header X-Proxy-External-IP ${proxy_external_ip};
    }
}
