ulid = "01KMTBEQ0BCSRP6HNRMKCZKD8H"
owner = "mockup.scientist"
mockup = true
merit = 5
requested_units = ["mast00"]

[target]
ra_hours = 0.571
dec_degrees = -27.144
name = "GD 16"
magnitude = 14.0
requested_exposure_duration = 1200.0
requested_number_of_exposures = 3

[target.science]
classification = "WD Pollution"
case = "Spectroscopic monitoring to characterize accreted planetary material. DeepSpec's 380-850nm bandpass enables simultaneous detection of Ca, Mg, Fe and Si absorption features from tidally disrupted planetesimals."

[spec_assignment]
instrument = "deepspec"

[spec_assignment.calibration]
lamp_on = true
filter = "ND3000"
