ulid = "01KMTBEQ0C3T1XBQZDYEA0AJKC"
owner = "mockup.scientist"
mockup = true
merit = 7
required_units = 1

[target]
ra_hours = 18.717
dec_degrees = 4.25
name = "WD 1840+042"
magnitude = 14.8
requested_exposure_duration = 1200.0
requested_number_of_exposures = 3

[target.science]
classification = "WD Pollution"
case = "Spectroscopic monitoring to characterize accreted planetary material. DeepSpec's 380-850nm bandpass enables simultaneous detection of Ca, Mg, Fe and Si absorption features from tidally disrupted planetesimals."

[spec_assignment]
instrument = "deepspec"
