ulid = "01KMTBEQ0BCSRP6HNRMKCZKD8J"
owner = "mockup.scientist"
mockup = true
merit = 6
required_units = 1

[target]
ra_hours = 13.883
dec_degrees = -9.267
name = "WD 1350-090"
magnitude = 15.8
requested_exposure_duration = 1800.0
requested_number_of_exposures = 3

[target.science]
classification = "WD Pollution"
case = "Spectroscopic monitoring to characterize accreted planetary material. DeepSpec's 380-850nm bandpass enables simultaneous detection of Ca, Mg, Fe and Si absorption features from tidally disrupted planetesimals."

[spec_assignment]
instrument = "deepspec"
