
#
# Generic settings
#
[settings]
    ulid = ''                       # generated at creation time
    owner = "arie"                  # valid user with canOwnTasks capability
    merit = 17                      # for sorting eligible tasks
    ready_to_guide_timeout = 600    # how long to wait for member units to achieve 'guiding'
    state = "new"

#
# A target section specifies:
# - The coordinates (either decimal or sexagesimal)
# - The required units.  This can be as simple or as complicated as needed :-)
#   Formally, units can be specified by their <site>:<building>:<ids>, where:
#   - <site>: a valid site moniker, e.g. wis (Weizmann), ns (Neot Smadar) or reh (Rehoboth, Namibia [https://www.google.com/maps/place/Rehoboth,+Namibia/@-23.3159864,17.0658873,7441m/data=!3m2!1e3!4b1!4m15!1m8!3m7!1s0x1bf53c7e6ed37521:0xd3b9e5a5a8ecb261!2sNamibia!3b1!8m2!3d-22.95764!4d18.49041!16zL20vMDVibXE!3m5!1s0x1c0c9b229a432cab:0x168c93e1201c691a!8m2!3d-23.3196141!4d17.0893798!16zL20vMDY1M2Iw?entry=ttu&g_ep=EgoyMDI0MTAyOS4wIKXMDSoASAFQAw%3D%3D])
#   - <building>: a valid building number or name (e.g. 'north', 'south', etc.) at the specified <site>.  Each building
#                 has a list of contained unit IDs, as in 'north': 1-10, 'south': 1-10
#   - <ids>: one or more (comma separated) unit IDs:
#      - 3 => [3]
#      - 2-4 => [2,3,4]
#      - 1,4,5-7,9 => [1,4,5,6,7,9]
#      - any-4 => any 4 units
#   - if no <site> is specified, it defaults to the 'local' site
#   - if no <building> is specified, the unit IDs are site-wise, not building-wise
#
#   Some valid examples:
#   - 'wis:w' - unit 'w' at 'wis' (Weizmann)
#   - ['ns:north:any-2', 'ns:south:8-10', 'reh:17']
#     - any two units in the 'north' building at Neot Smadar
#     - units 8,9 and 10 in the 'south' building at Neot Smadar
#     - unit 17 at Rehoboth (Namibia)
#     - A total of 6 units are specified
#
#    - quorum: If less than this are ready (operational and reached guiding), the task is aborted.
#
[target]
    name = 'whatever name'  # optional
    ra = "10:12:34.56"      # Decimal (e.g. 12.345) or Sexagesimal (HH:MM:SS.FFF)
    dec = "-12:34:56.7"     # Decimal (e.g. -23.45) or Sexagesimal (DD:MM:SS.FFF)
    magnitude = 16.23       # optional - Estimated magnitude of researched object
    magnitude_band = 'g'    # optional - band/filter identifier
    units = "w"             # List of required units
    quorum = 1              # minimal number of units mandatory for this target
    allocated_units = []    # to be filled-in by the scheduler or manually before we have a scheduler

[spec]
    instrument = "highspec" # one of 'highspec', 'high', 'deepspec', 'deep']
    exposure = 600.0        # seconds
    binning_x = 1           # optional (default: 1), one of [1, 2, 4]
    binning_y = 2           # optional (default: 1), one of [1, 2, 4]
    gratings = ['Ca', 'Mg'] # if multiple, take subsequent exposures withing same 'guiding' sequence

[spec.lamp]
    on = true
    filter = "ND3000"

[constraints.moon]
    max_phase = 53          # [percent]
    min_distance = 27       # [degrees]

[constraints.airmass]
    max = 1.3

[constraints.seeing]
    max = 2.8

[constraints.time_window]
    # from = datetime       # optional [datetime]
    # to = datetime         # optional [datetime]
