ulid = "01KMTBEQ0N5H8YN3NCSJD2G2KY"
owner = "mockup.scientist"
mockup = true
merit = 1
required_units = 1
approved = true

[target]
ra_hours = 13.01
dec_degrees = 27.6
name = "WD 1257+278 B"
magnitude = 16.2
requested_exposure_duration = 1800.0
requested_number_of_exposures = 3

[target.science]
classification = "WD Exoplanet Transit"
case = "Photometric and spectroscopic monitoring for transiting debris and planetesimals. Target shows irregular transit-like dimming events consistent with disintegrating rocky bodies in a close-in orbit."

[spec_assignment]
instrument = "deepspec"

[[events]]
what = "approved"
detail = "mockup"
when = "2026-03-28T13:52:05Z"
